dist: focal
language: python
services: docker

env:
  global:
    - ROLE_NAME: firewall
  matrix:
    - MOLECULE_DISTRIBUTION: centos6
    - MOLECULE_DISTRIBUTION: centos7
    - MOLECULE_DISTRIBUTION: centos8

install:
  - pip install molecule==3.0.8 docker yamllint ansible-lint ansible

before_script:
  # Remove "ansible-role-" prefix from role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - ansible-galaxy install -n -r molecule/default/requirements.yml
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
