language: python
services: docker

env:
  global:
    - ROLE_NAME: firewall
  matrix:
    - MOLECULE_DISTRIBUTION: centos6
    - MOLECULE_DISTRIBUTION: centos7
    - MOLECULE_DISTRIBUTION: centos8

install:
  - pip install --no-deps molecule==3.0.6 ansible-lint
  - >-
    pip install
        Jinja2
        PyYAML
        ansible-base
        cerberus
        click
        click-completion
        click-help-colors
        colorama
        cookiecutter
        docker==4.2.2
        flake8
        paramiko
        pexpec
        pluggy
        pre-commit
        python-gilt
        sh
        tabulate
        tree-format
        yamllint

before_script:
  # Remove "ansible-role-" prefix from role name
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
