- name: IPTABLES | Copy iptables template
  template:
    src: "{{ _firewall_template }}.j2"
    dest: "{{ _firewall_config_dir }}/{{ _firewall_config_file }}"
    backup: yes
    owner: root
    group: root
    mode: 0600
    validate: iptables-restore --test %s
  notify: restart firewall
  tags:
    - firewall
    - firewall_config

- name: IPTABLES | Ensure iptables is enabled and started
  service:
    name: iptables
    enabled: yes
    state: started
  tags:
    - firewall
