- name: PF | Copy pf rules
  template:
    src: "{{ _firewall_template }}"
    dest: "{{ _firewall_config_dir }}/{{ _firewall_config_file }}"
    owner: root
    group: wheel
    mode: '0644'
    validate: /sbin/pfctl -v -n -f %s
  notify: reload pf
  tags:
    - firewall
    - firewall_config
