- name: PF | Copy launchtl job file
  template:
    src: pfctl.plist.j2
    dest: /Library/LaunchDaemons/{{ _firewall_job_name }}.plist
    mode: '0644'
  register: launchtl_job_file
  notify: reload pf
  tags:
    - firewall

- name: PF | Copy pf rules
  template:
    src: "{{ _firewall_template }}"
    dest: "{{ _firewall_config_dir }}/{{ _firewall_config_file }}"
    owner: root
    group: wheel
    mode: '0644'
    validate: /sbin/pfctl -v -n -f %s
  notify: reload pf
  tags:
    - firewall
    - firewall_config
