- name: IPTABLES | Copy iptables template
  template:
    src: "{{ firewall_template }}.j2"
    dest: "{{ firewall_config_dir }}/{{ firewall_config_file }}"
    backup: true
    owner: root
    group: root
    mode: 0600
    validate: iptables-restore --test %s
  notify: restart firewall
  tags:
    - firewall
    - fwconfig
    - fwrules

- name: IPTABLES | Ensure iptables is enabled and started
  service:
    name: iptables
    enabled: true
    state: started
  tags: firewall
