---
- name: FIREWALL | Check if contract exists
  ansible.builtin.stat:
    path: /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
  register: _nf_conntrack_tcp_be_liberal

- name: FIREWALL | Fix dropped ssh sessions configure kernel
  ansible.posix.sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  when: _nf_conntrack_tcp_be_liberal.stat.exists
  tags:
    - ufw-fix-dropped-ssh-sessions-configure-kernel
