- name: Set variables for Red Hat
  include_vars: "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
  when: ansible_facts.os_family == 'RedHat'
  tags:
    - firewall
    - always

- name: Set variables for Debian
  include_vars: "{{ ansible_facts.os_family }}.yml"
  when: ansible_facts.os_family == 'Debian'
  tags:
    - firewall
    - always

- include_tasks: setup-{{ ansible_facts.os_family }}.yml
  tags:
    - firewall

- include_tasks: configure-{{ firewall_name }}.yml
  tags:
    - firewall
    - firewall_config
    - fwconfig
