---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: firewall

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: firewall

- name: Copy iptables template
  template:
    src: iptables.j2
    dest: "{{ firewall_config_dir }}/{{ firewall_config_file }}"
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: reload iptables
  tags: firewall

- name: Ensure iptables is enabled and started
  service: name=iptables enabled=yes state=started
  tags: firewall
