- name: Set variables for Red Hat
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'RedHat'
  tags:
    - firewall
    - always

- name: Set variables for Debian
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'
  tags:
    - firewall
    - always

- include: setup-{{ ansible_os_family }}.yml
  tags:
    - firewall

- include: configure-{{ firewall_name }}.yml
  tags:
    - firewall
