---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version <= 6
  tags: firewall

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: firewall

- include: configure-iptables.yml
  when: >
    (ansible_os_family == 'RedHat' and ansible_distribution_major_version <= 6) or
    ansible_os_family == 'Debian'
  tags: firewall

- include: configure-firewalld.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == 7
  tags: firewall