---
- name: ensure firewalld is installed
  ansible.builtin.yum:
    name: firewalld
    state: present
  tags: firewalld

- name: ensure firewalld is enabled and started
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: started
  tags: firewalld
