---
- name: FIREWALL | Facts
  ansible.builtin.set_fact:
    kernel_version: "{{ ansible_kernel | regex_search('^([0-9]+\\.[0-9]+\\.[0-9]+)') }}"
  tags:
    - firewall

# see https://askubuntu.com/a/1064533/261010, https://www.spinics.net/lists/netfilter-devel/msg55682.html
- name: FIREWALL | Fix netfilter firewall
  ansible.builtin.include_tasks: fix-dropped-ssh-sessions.yml
  when:
    - kernel_version is version('4.14', '>=')
    - kernel_version is version('5', '<')
  tags:
    - firewall

- name: FIREWALL | Install dependencies
  ansible.builtin.apt:
    pkg: ["{{ item }}"]
    state: "present"
    update_cache: true
    cache_valid_time: 5400
  with_items: "{{ ufw_dependencies }}"
  tags:
    - firewall

- name: FIREWALL | Ensure ufw is enabled and started
  ansible.builtin.service:
    name: ufw
    enabled: yes
    state: started
  tags:
    - firewall
