---
- name: Install iptables (Debian)
  apt: name=iptables state=latest

- name: Set iptables directory (Debian)
  set_fact:
    firewall_config_dir: "/etc/"
    firewall_config_file: "iptables.rules"
  tags: [ 'firewall' , 'fwconfig']


- name: Set firewall template name (Debian)
  set_fact:
    firewall_template: "iptables"
  tags: [ 'firewall' , 'fwconfig']

- name: Copy iptables load script (Debian)
  template:
    src: iptablesload.j2
    dest: /etc/if-pre-up.d/iptablesload
    owner: root
    group: root
    mode: 0700