---
- name: Install iptables (Red Hat)
  yum: name=iptables state=latest enablerepo=base

- name: Set iptables directory (Red Hat)
  set_fact:
    firewall_config_dir: "/etc/sysconfig"
    firewall_config_file: "iptables"
  tags:
    - firewall
    - fwconfig

- name: Set firewall template name (Red Hat)
  set_fact:
    firewall_template: "iptables"
  when: ansible_distribution != 'XenServer'
  tags:
    - firewall
    - fwconfig

- name: Set firewall template name (XenServer)
  set_fact:
    firewall_template: "iptables-{{ ansible_distribution }}"
  when: ansible_distribution == 'XenServer'
  tags:
    - firewall
    - fwconfig
