---
- name: Install iptables (Red Hat)
  yum: name=iptables state=latest

- name: Set iptables directory (Red Hat)
  set_fact:
    firewall_config_dir: "/etc/sysconfig"
    firewall_config_file: "iptables"