- name: DEBIAN | Install iptables
  ansible.builtin.apt:
    name: iptables
    state: latest
  tags:
    - firewall

- name: DEBIAN | Copy iptables load script
  ansible.builtin.template:
    src: iptablesload.j2
    dest: /etc/if-pre-up.d/iptablesload
    owner: root
    group: root
    mode: "0700"
  tags:
    - firewall
    - firewall_config
