- name: RHEL | Install {{ firewall_name }}
  yum:
    name: "{{ firewall_name }}"
    state: latest

- name: RHEL | Set firewall template name (XenServer)
  set_fact:
    firewall_template: "iptables-{{ ansible_distribution }}"
  when: ansible_distribution == 'XenServer'
  tags:
    - firewall
    - fwconfig
