- name: (Heandler) Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: (Heandler) Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: (Heandler) Reload ufw
  community.general.ufw:
    state: reloaded

- name: (Heandler) Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
