- name: reload firewall
  service:
    name: "{{ _firewall_name }}"
    state: reloaded

- name: restart firewall
  service:
    name: "{{ _firewall_name }}"
    state: restarted

- name: reload pf
  command: /sbin/pfctl -E -f {{ _firewall_config_dir }}/{{ _firewall_config_file }}
  async: 10
  poll: 0
