- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
